# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-21 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20180411_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexusercertificate',
            options={'verbose_name': '员工证书明细', 'verbose_name_plural': '员工证书明细'},
        ),
    ]
