# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rank13', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficent', models.DecimalField(decimal_places=2, default=0, help_text='系数', max_digits=4, verbose_name='系数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('is_special', models.BooleanField(default=False, verbose_name='是否为特殊指定系数')),
                ('rank13coefficent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rank13.Rank13Coefficent', verbose_name='等级行员关联系数')),
                ('rank13demands', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rank13.Rank13Demands', verbose_name='岗位等级及岗位要求')),
            ],
            options={
                'verbose_name': '员工系数',
                'verbose_name_plural': '员工系数',
            },
        ),
    ]
