# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='大庆农商银行', help_text='组织', max_length=30, unique=True, verbose_name='组织')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='岗位', max_length=30, unique=True, verbose_name='岗位')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='Rank13Coefficent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, help_text='等次', verbose_name='等次')),
                ('level', models.IntegerField(default=1, help_text='级次', verbose_name='级次')),
                ('coefficent', models.DecimalField(decimal_places=2, default=0, help_text='系数', max_digits=4, verbose_name='系数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('agent', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='agent_rank13coefficent', to='rank13.Agent', verbose_name='组织')),
                ('post', models.ForeignKey(help_text='岗位', on_delete=django.db.models.deletion.CASCADE, related_name='post_rank13coefficent', to='rank13.Post', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '行员等级对应岗位系数',
                'verbose_name_plural': '行员等级对应岗位系数',
            },
        ),
        migrations.CreateModel(
            name='Rank13Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, help_text='等次', verbose_name='等次')),
                ('level', models.IntegerField(blank=True, help_text='级次', null=True, verbose_name='级次')),
                ('demandyears', models.IntegerField(default=1, help_text='金融从业年限要求', verbose_name='金融从业年限要求')),
                ('educationdemands', models.IntegerField(choices=[(1, '高中（中专）及以下'), (2, '大学专科'), (3, '大学本科'), (4, '硕士研究生'), (5, '博士研究生及以上')], default=1, help_text='学历: 1高中（中专）及以下,2(大学专科),3(大学本科),4(硕士研究生),5(博士研究生及以上)', verbose_name='学历')),
                ('primccbpdemands', models.IntegerField(default=0, help_text='从业资格证书要求', verbose_name='从业资格证书要求')),
                ('titledemands', models.IntegerField(choices=[(1, '无'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, help_text='职称: 1(无),2(初级),3(中级),4(高级)', verbose_name='职称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('agent', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='agent_demand', to='rank13.Agent', verbose_name='组织')),
                ('post', models.ForeignKey(help_text='岗位', on_delete=django.db.models.deletion.CASCADE, related_name='post_demand', to='rank13.Post', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '行员等级与任职资格要求',
                'verbose_name_plural': '行员等级与任职资格要求',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rank13demands',
            unique_together=set([('rank', 'level')]),
        ),
    ]
