# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 13:17
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idcardnumber', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('joinedyears', models.DateField(blank=True, null=True, verbose_name='参加工作年月')),
                ('education', models.IntegerField(choices=[(1, '高中（中专）及以下'), (2, '大学专科'), (3, '大学本科'), (4, '硕士研究生'), (5, '博士研究生及以上')], default=1, help_text='学历: 1高中（中专）及以下,2(大学专科),3(大学本科),4(硕士研究生),5(博士研究生及以上)', verbose_name='学历')),
                ('title', models.IntegerField(choices=[(1, '无'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, help_text='职称: 1(无),2(初级),3(中级),4(高级)', verbose_name='职称')),
                ('internel_trainer', models.IntegerField(choices=[(1, '无'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, help_text='内训师: 1(无),2(初级),3(中级),4(高级)', verbose_name='内训师')),
                ('cmanagerlevel', models.IntegerField(choices=[(1, '无'), (2, '一等'), (3, '二等'), (4, '三等')], default=1, help_text='客户经理等次: 1(无),2(一等),3(二等),4(三等)', verbose_name='客户经理等次')),
                ('cmanagerrank', models.IntegerField(choices=[(1, '无'), (2, '初级'), (3, '中级'), (4, '高级'), (5, '资深')], default=1, help_text='客户经理级次: 1(无),2(初级),3(中级),4(高级),5(资深)', verbose_name='客户经理级次')),
                ('clerkrank', models.IntegerField(choices=[(1, '无'), (2, '见习柜员'), (3, '初级柜员'), (4, '中级柜员'), (5, '高级柜员'), (6, '资深柜员')], default=1, help_text='柜员等级: 1(无),2(见习),3(初级),4(中级),5(高级),6(资深)', verbose_name='柜员等级')),
                ('primccbp', models.IntegerField(default=0, help_text='初级银行从业', verbose_name='初级银行从业')),
                ('intermediateccbp', models.IntegerField(default=0, help_text='中级银行从业', verbose_name='中级银行从业')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
