# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcardnumber', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('depart', models.CharField(blank=True, max_length=30, null=True, verbose_name='机构')),
                ('post', models.CharField(blank=True, max_length=11, null=True, verbose_name='岗位')),
                ('joinedyears', models.DateField(blank=True, null=True, verbose_name='参加工作年月')),
                ('yearsofworking', models.IntegerField(blank=True, default=1, null=True, verbose_name='工龄')),
                ('ywslary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工龄津贴')),
                ('education', models.CharField(blank=True, max_length=30, null=True, verbose_name='学历')),
                ('edslary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='学历津贴')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='职称')),
                ('tislary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='职称津贴')),
                ('itrainer', models.CharField(blank=True, max_length=30, null=True, verbose_name='内训师')),
                ('itslary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='内训师津贴')),
                ('cmanagerrank', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户经理级别')),
                ('cmslary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='客户经理津贴')),
                ('fltotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='津贴合计')),
                ('rank', models.IntegerField(default=1, help_text='行员等级', verbose_name='行员等级')),
                ('coefficent', models.DecimalField(decimal_places=2, default=0, help_text='系数', max_digits=4, verbose_name='系数')),
                ('basesalary', models.DecimalField(decimal_places=2, default=0, help_text='基本薪酬基数', max_digits=10, verbose_name='基本薪酬基数')),
                ('basesalarythismonth', models.DecimalField(decimal_places=2, default=0, help_text='基本薪酬', max_digits=10, verbose_name='基本薪酬')),
                ('privateaffairleavedays', models.IntegerField(default=0, help_text='事假天数', verbose_name='事假天数')),
                ('sickleavedays', models.IntegerField(default=0, help_text='病假天数', verbose_name='病假天数')),
                ('basesalarythismonthwithleaves', models.DecimalField(decimal_places=2, default=0, help_text='基本薪酬病事假扣除', max_digits=10, verbose_name='基本薪酬病事假扣除')),
                ('basesalaryresult', models.DecimalField(decimal_places=2, default=0, help_text='基本薪酬结果', max_digits=10, verbose_name='基本薪酬结果')),
                ('welfareresult', models.DecimalField(decimal_places=2, default=0, help_text='福利薪酬结果', max_digits=10, verbose_name='福利薪酬结果')),
                ('basesalaryadd', models.DecimalField(decimal_places=2, default=0, help_text='补发基本薪酬', max_digits=10, verbose_name='补发基本薪酬')),
                ('welfareresultadd', models.DecimalField(decimal_places=2, default=0, help_text='补发福利薪酬', max_digits=10, verbose_name='补发福利薪酬')),
                ('totalsalaryresult', models.DecimalField(decimal_places=2, default=0, help_text='薪酬合计', max_digits=10, verbose_name='薪酬合计')),
                ('endowmentinsurance', models.DecimalField(decimal_places=2, default=0, help_text='养老保险', max_digits=10, verbose_name='养老保险')),
                ('medicalinsurance', models.DecimalField(decimal_places=2, default=0, help_text='医疗保险', max_digits=10, verbose_name='医疗保险')),
                ('unemploymentinsurance', models.DecimalField(decimal_places=2, default=0, help_text='失业保险', max_digits=10, verbose_name='失业保险')),
                ('housingprovidentfund', models.DecimalField(decimal_places=2, default=0, help_text='住房公积金', max_digits=10, verbose_name='住房公积金')),
                ('totlainsuranceandfund', models.DecimalField(decimal_places=2, default=0, help_text='三险一金合计', max_digits=10, verbose_name='三险一金合计')),
                ('totalpayamount', models.DecimalField(decimal_places=2, default=0, help_text='应发薪酬', max_digits=10, verbose_name='应发薪酬')),
                ('personaltax', models.DecimalField(decimal_places=2, default=0, help_text='个人所得税', max_digits=10, verbose_name='个人所得税')),
                ('partymemberdues', models.DecimalField(decimal_places=2, default=0, help_text='代扣党费', max_digits=10, verbose_name='代扣党费')),
                ('otherdeductions', models.DecimalField(decimal_places=2, default=0, help_text='其他扣除项', max_digits=10, verbose_name='其他扣除项')),
                ('finalpayingamount', models.DecimalField(decimal_places=2, default=0, help_text='实发薪酬', max_digits=10, verbose_name='实发薪酬')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrainfo', models.TextField(default='4月工资记录', verbose_name='备注')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='记录日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
        ),
    ]
