# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='fsalary',
            name='srecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.SalaryRecord', verbose_name='月工资记录'),
        ),
        migrations.AddField(
            model_name='fsalary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
