# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20180411_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsalary',
            name='depart',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='机构'),
        ),
        migrations.AlterField(
            model_name='fsalary',
            name='post',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='岗位'),
        ),
    ]
