# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20180419_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fsalary',
            options={'verbose_name': '工资明细', 'verbose_name_plural': '工资明细'},
        ),
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'verbose_name': '月工资记录', 'verbose_name_plural': '月工资记录'},
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='baseandwelfareaddfile',
            field=models.FileField(help_text='补发基本福利薪酬记录', null=True, upload_to='salarybase', verbose_name='补发基本福利薪酬记录'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='checkonworkfile',
            field=models.FileField(help_text='病假事假记录', null=True, upload_to='salarybase', verbose_name='病假事假记录'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='insuranceandfundfile',
            field=models.FileField(help_text='五险一金记录', null=True, upload_to='salarybase', verbose_name='五险一金记录'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='status',
            field=models.CharField(choices=[('UNCOMPELTE', '尚未完成本月工资核算'), ('BASESALARYINITCOMPLETE', '已生成基础工资与福利薪酬'), ('CHECKONWORKATTENDANCECOMPLETE', '完成考勤录入'), ('TOTALSALARYCOMPLETE', '已生成薪酬合计'), ('INSURANCEANDFUNDCOMPELTE', '已经录入五险一金并生成应发薪酬'), ('TAXANDOTHERDEDUCTIONS', '已完成税费及其他扣除项录入生成实发薪酬')], default='UNCOMPELTE', max_length=60, verbose_name='工资记录状态'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='taxandotherdeductionfile',
            field=models.FileField(help_text='税费及其他扣除项记录', null=True, upload_to='salarybase', verbose_name='税费及其他扣除项记录'),
        ),
    ]
