# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20180421_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='baseandwelfareaddfile',
            field=models.FileField(blank=True, help_text='补发基本福利薪酬记录', null=True, upload_to='salarybase', verbose_name='补发基本福利薪酬记录'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='checkonworkfile',
            field=models.FileField(blank=True, help_text='病假事假记录', null=True, upload_to='salarybase', verbose_name='病假事假记录'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='insuranceandfundfile',
            field=models.FileField(blank=True, help_text='五险一金记录', null=True, upload_to='salarybase', verbose_name='五险一金记录'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='taxandotherdeductionfile',
            field=models.FileField(blank=True, help_text='税费及其他扣除项记录', null=True, upload_to='salarybase', verbose_name='税费及其他扣除项记录'),
        ),
    ]
