# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_auto_20180427_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='extrainfo',
            field=models.TextField(blank=True, default='5月工资记录', null=True, verbose_name='备注'),
        ),
    ]
