# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-21 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_useruploadbasefiles_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useruploadbasefiles',
            options={'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
    ]
