# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 09:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='测评程序', max_length=60, null=True, verbose_name='测评程序')),
                ('appraisalchoices', models.CharField(blank=True, choices=[('QUALIFICATIONS', '任职资格测评'), ('DEMOCRATICAPPRAISAL', '民主测评'), ('LEADERVALUATE', '有权人测评')], max_length=60, null=True, verbose_name='测评种类')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '测评程序',
                'verbose_name_plural': '测评程序',
            },
        ),
        migrations.CreateModel(
            name='AppraisalTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='测评得分', verbose_name='测评得分')),
                ('qualifications', models.CharField(blank=True, help_text='测评结果', max_length=18, null=True, verbose_name='测评结果')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('appraisalprocedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.AppraisalProcedure', verbose_name='测评程序')),
                ('appraisedperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise_person', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('evaluateperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_person', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '测评票',
                'verbose_name_plural': '测评票',
            },
        ),
        migrations.CreateModel(
            name='EvaluateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificationsscore', models.IntegerField(default=0, help_text='任职资格测评得分', verbose_name='任职资格测评得分')),
                ('democraticappraisalscore', models.IntegerField(default=0, help_text='民主测评得分', verbose_name='民主测评得分')),
                ('leaderevaluatescore', models.IntegerField(default=0, help_text='有权人测评得分', verbose_name='有权人测评得分')),
                ('qualifications', models.CharField(blank=True, help_text='任职资格测评结果', max_length=18, null=True, verbose_name='任职资格测评结果')),
                ('democraticappraisal', models.CharField(blank=True, help_text='民主测评结果', max_length=18, null=True, verbose_name='民主测评结果')),
                ('leaderevaluate', models.CharField(blank=True, help_text='有权人测评结果', max_length=18, null=True, verbose_name='有权人测评结果')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评价结果',
                'verbose_name_plural': '评价结果',
            },
        ),
    ]
