# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_auto_20180504_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateresult',
            name='bankleaderresult',
            field=models.CharField(blank=True, help_text='主管行长给分结果', max_length=18, null=True, verbose_name='主管行长给分结果'),
        ),
        migrations.AddField(
            model_name='evaluateresult',
            name='bankleadersocre',
            field=models.IntegerField(blank=True, default=0, help_text='主管行长给分', null=True, verbose_name='主管行长给分'),
        ),
        migrations.AddField(
            model_name='evaluateresult',
            name='ceoresult',
            field=models.CharField(blank=True, help_text='董事长给分结果', max_length=18, null=True, verbose_name='董事长给分结果'),
        ),
        migrations.AddField(
            model_name='evaluateresult',
            name='ceoscore',
            field=models.IntegerField(blank=True, default=0, help_text='董事长给分', null=True, verbose_name='董事长给分'),
        ),
        migrations.AddField(
            model_name='evaluateresult',
            name='departleaderesult',
            field=models.CharField(blank=True, help_text='部门领导给分结果', max_length=18, null=True, verbose_name='部门领导给分结果'),
        ),
        migrations.AddField(
            model_name='evaluateresult',
            name='departleaderscore',
            field=models.IntegerField(blank=True, default=0, help_text='部门领导给分', null=True, verbose_name='部门领导给分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='democraticappraisalscore',
            field=models.IntegerField(blank=True, default=0, help_text='民主测评得分', null=True, verbose_name='民主测评得分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='leaderevaluatescore',
            field=models.IntegerField(blank=True, default=0, help_text='有权人测评得分', null=True, verbose_name='有权人测评得分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='qualificationsscore',
            field=models.IntegerField(blank=True, default=0, help_text='任职资格测评得分', null=True, verbose_name='任职资格测评得分'),
        ),
    ]
