# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_auto_20180504_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalticket',
            name='appraisalprocedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisalticket_appraisalprocedure', to='evaluate.AppraisalProcedure', verbose_name='测评程序'),
        ),
    ]
