# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0004_auto_20180507_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalticket',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='测评得分', max_digits=6, verbose_name='测评得分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='bankleadersocre',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='主管行长给分', max_digits=6, null=True, verbose_name='主管行长给分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='ceoscore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='董事长给分', max_digits=6, null=True, verbose_name='董事长给分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='democraticappraisalscore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='民主测评得分', max_digits=6, null=True, verbose_name='民主测评得分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='departleaderscore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='部门领导给分', max_digits=6, null=True, verbose_name='部门领导给分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='leaderevaluatescore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='有权人测评得分', max_digits=6, null=True, verbose_name='有权人测评得分'),
        ),
        migrations.AlterField(
            model_name='evaluateresult',
            name='qualificationsscore',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='任职资格测评得分', max_digits=6, null=True, verbose_name='任职资格测评得分'),
        ),
    ]
