# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-08 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0005_auto_20180507_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='state',
            field=models.CharField(blank=True, choices=[('UNLOCK', '未锁定'), ('LOCK', '锁定')], default='UNLOCK', max_length=60, null=True, verbose_name='测评状态'),
        ),
    ]
