# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 13:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='机构', max_length=30, verbose_name='机构')),
                ('desc', models.TextField(default='', help_text='机构描述', null=True, verbose_name='机构描述')),
                ('dept_type', models.IntegerField(choices=[(1, '机关'), (2, '支行')], help_text='组织', verbose_name='组织')),
                ('basesalary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.CreateModel(
            name='IndexUserDepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_user', to='depart.DepartDetail', verbose_name='部门-用户')),
            ],
            options={
                'verbose_name': '用户-机构',
                'verbose_name_plural': '用户-机构',
            },
        ),
    ]
