# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-21 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0002_auto_20180411_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departdetail',
            options={'verbose_name': '部门管理', 'verbose_name_plural': '部门管理'},
        ),
        migrations.AlterModelOptions(
            name='indexuserdepart',
            options={'verbose_name': '员工所在部门', 'verbose_name_plural': '员工所在部门'},
        ),
        migrations.AlterField(
            model_name='indexuserdepart',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_user', to='depart.DepartDetail', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='indexuserdepart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_depart', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
