# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0003_auto_20180421_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departdetail',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='机构描述', null=True, verbose_name='机构描述'),
        ),
        migrations.AlterField(
            model_name='departdetail',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='主管领导', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_leader', to=settings.AUTH_USER_MODEL, verbose_name='主管领导'),
        ),
        migrations.AlterField(
            model_name='departdetail',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='部门经理', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to=settings.AUTH_USER_MODEL, verbose_name='部门经理'),
        ),
    ]
